theme: jekyll-theme-modernist
title: NorthShore University HealthSystem
description: Center for Psychiatric Genomics
navbar-links:
  Home: "https://rbutleriii.github.io/center_for_psychiatric_genomics"
  2019:
    - iMG and AD: "https://rbutleriii.github.io/center_for_psychiatric_genomics/iMicroglia.html"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
